from corr import parse_corr_problem, corr_valid_methods
from thresh import parse_thresh_problem, thresh_valid_methods
from trans import parse_trans_problem, trans_valid_methods
from hand_fft import parse_hand_fft_problem, hand_fft_valid_methods
